### ISSUE TITLE
Unused argument `sig` in `mdns_repeater_shutdown`

### ISSUE THREAD

**Issue by KizzyCode** [geekman/mdns-repeater#12]
The function argument `sig` in `mdns_repeater_shutdown` is unused and raises a warning with `-Wextra`.

This can e.g. be fixed by explicitly casting the argument to `void`:
```c
static void mdns_repeater_shutdown(int sig) {
    shutdown_flag = 1;
}
```

would become

```c
static void mdns_repeater_shutdown(int sig) {
    (void)sig;
    shutdown_flag = 1;
}
```

Thank you for maintaining `mdns-repeater`! 😊

**Comment by kennylevinsen** [comment]
Sorry for delay, fixed in master.

**Comment by KizzyCode** [comment]
Nothing to excuse here IMO; thank you very much!
