### ISSUE TITLE
Original code's url no longer valid at bitbucket

### ISSUE THREAD

**Issue by seidnerj** [geekman/mdns-repeater#13]
The original author has moved the code from bitbucket (https://bitbucket.org/geekman/mdns-repeater) to github (https://github.com/geekman/mdns-repeater). 

I had a lot of trouble finding this fork since the bitbucket link from which this was forked is invalid and there is no connection between this fork and the (now existing) repo in Github, mentioned above.

If possible, this should somehow be fixed so there's proper documented lineage of the code.

**Comment by kennylevinsen** [comment]
I updated the link.

The original repo was mercurial, so this repo and geekman's recent-ish move are two different mercurial-to-git conversions and as a result the git commit IDs do not match. I'd have to rewrite master to be a clean fork. Maybe it could be established as a github UI fork button thing, but I don't personally care that much for that.

**Comment by kennylevinsen** [comment]
As an aside, I opened an issue about reintegrating into upstream: https://github.com/geekman/mdns-repeater/issues/3

**Comment by seidnerj** [comment]
Cool!

**Comment by seidnerj** [comment]
I guess you’ve migrated this to the original repo, great! the above link to issue #3 makes it all the more confusing :)

**Comment by kennylevinsen** [comment]
Hah, yes. We'll have to get @geekman to change it now. :)

**Comment by seidnerj** [comment]
👍😁
