### ISSUE TITLE
Only works when debugging with -f

### ISSUE THREAD

**Issue by cerahmed** [geekman/mdns-repeater#19]
Hi there,

Thanks for the great tool, I can finally use mDNS over Wiregurad VPN!
I'm not sure I quite understand how I can install it though.

I cloned this repo into my RPi, then ran "make", which created a new folder with the mdns-repeater tool in it.
I ran "./mdns-repeater eth0 wg0", nothing happens. But when I ran "./mdns-repeater -f eth wg0", it opens the debugger and the repeating actually works.

Am I doing it right? Should I run it manually as a service/daemon or is my installation wrong?

**Comment by geekman** [comment]
Hi, what do you mean by "nothing happens"? By default, if you don't specify `-f`, it should continue to run in the background as a daemon.
