### ISSUE TITLE
make - Mercurial issues (?)

### ISSUE THREAD

**Issue by ghost** [geekman/mdns-repeater#2]
Hi,

I tried making this project locally and am hit with the errors if I installed Mercurial:

```
abort: no repository found in '/home/cj/workspace/mdns-repeater' (.hg not found)!
abort: no repository found in '/home/cj/workspace/mdns-repeater' (.hg not found)!
```

I do not know if this is an issue from moving the project to git since I have never used Mercurial.

Without Mercurial installed, I get the following:

```
/bin/sh: 1: hg: not found
/bin/sh: 1: hg: not found
cc -s  mdns-repeater.o   -o mdns-repeater
```

Seems like it did compile, however.

**Comment by kennylevinsen** [comment]
Ah, yeah, the original project this is a fork from used mercurial, and I did not update the makefile.

79d399a changes the Makefile so that the git sha is used as revision instead.
