### ISSUE TITLE
[feature request] whole 224.0.0.0/4 support

### ISSUE THREAD

**Issue by hippi-viking** [geekman/mdns-repeater#4]
Hi Kenny,

Do you think it is possible to extend the forwarded multicast range to the whole 224.0.0.0/4 subnet - or at least to include 239.255.255.250 to make SSDP work; and how difficult would it be to modify mdns-repeater to do this?

Thanks,
István

**Comment by kennylevinsen** [comment]
I am unfamiliar with SSDP, but while it is unrelated to mDNS, you can try changing the IP and port at the top of mdns-repeater.c (https://github.com/kennylevinsen/mdns-repeater/blob/79d499a9df8ca6f86694aa0f629c3ebba9d3b5ae/mdns-repeater.c#L38) to those of SSDP, and just run two mdns-repeater instances (one for mDNS, one for SSDP).

You can report back if that works for you and close the issue.

Forwarding a full subnet is out of scope of this project. PR welcome for making the port and IP configurable as a command-line option though.

**Comment by hippi-viking** [comment]
Thanks for the fast response!
As far as I know SSDP is very similar to mDNS but instead of 224.0.0.251:5353 it uses 239.255.255.250:1900 but I am fairly new to multicast routing, just trying to get it working across subnets at home. :)
Your solution about running two instances sounds like a good fix. It should be working that way, please close the issue then.
I will try to modify the script for parameterized IP and port when time allows.

**Comment by hippi-viking** [comment]
Seems like there is a [tool](https://github.com/sonicsnes/udp-broadcast-relay-redux) already that does have configurable addresses and ports!
