### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by alonam** [geekman/mdns-repeater#8]
Hi

Can you please use a permissive license like MIT?

Thank you

**Comment by kennylevinsen** [comment]
Why? A compelling reason should be provided for such a significant change.

But, no, I do not have the legal right to change the license. Such a change requires explicit permission from all contributors (including the original author). Closing as no reason for all that work was presented.

**Comment by alonam** [comment]
On second thought, you are absolutely right. There's no reason to change the license.
