### ISSUE TITLE
Running mdns-repeater as service in Debian

### ISSUE THREAD

**Issue by sjoerdj** [geekman/mdns-repeater#9]
Hi, I really like this great piece of software, but unfurtunately I cannot get it running as a service without failing after a while. I am using the following mdns-repeater.service file:

[Unit]
Description=mDNS Repeater
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
ExecStart=/home/user/mdns-repeater/mdns-repeater eth0 tun0

[Install]
WantedBy=multi-user.target

Problem is that:
- When I start the service with "ExecStart=/home/user/mdns-repeater/mdns-repeater eth0 tun0" (without attribute "-f"), Debian reports the service as "inactive (dead)" when I check the service's status;
- When I start the service with "ExecStart=/home/user/mdns-repeater/mdns-repeater eth0 tun0 -f" (with attribute "-f") it will crash after a while and won't restart automatically as Debian complains about "start request repeated too quickly".

Could you please provide me with the best practice settings for an mdns-repeater.service in Debian that will make mdns-repeater run as a stable service? Thanks a lot!

**Comment by kennylevinsen** [comment]
If it crashes you will need to provide information about the crash in the form of a backtrace (see coredumpctl).

Any foreground command that works in your shell should do. You shouldn't be running system services out of your home folder though. Put it in /usr/local/bin or something.

**Comment by sjoerdj** [comment]
Thanks, Kenny! Running it from /usr/local/bin did the trick. By the way, in order to prevent syslog from becoming overflowed, I added the following line to the service section in the mdns-repeater.service file:

StandardOutput=null
